#Get JWT
POST http://localhost:5000/auth/login
Content-Type: application/json

{"username": "api", "password": "AH31LP#"}

###

# Get secured data
GET http://127.0.0.1:5000/api/v1/users
Content-Type: application/json
Authorization: Bearer [тут має бути access token з попереднього запиту без квадратних]

###

# Refresh Auth

POST http://localhost:5000/auth/refresh
Content-Type: application/json
Authorization: Bearer [тут має бути refresh token з попереднього запиту без квадратних]