"""empty message

Revision ID: 9b549851010c
Revises: fe12ac384bb3
Create Date: 2023-02-27 17:14:52.266111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b549851010c'
down_revision = 'fe12ac384bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contacs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('address_en', sa.String(length=200), nullable=True),
    sa.Column('facebook', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('viber', sa.String(length=100), nullable=True),
    sa.Column('google_maps', sa.String(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Counter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_symbol', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('locale', sa.String(length=100), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Current needs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('media_path', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Docs and reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statutes', sa.String(), nullable=True),
    sa.Column('ownership_structure', sa.String(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('bank_account_holder_certificate', sa.String(), nullable=True),
    sa.Column('certificate_of_nonprofit_organization', sa.String(), nullable=True),
    sa.Column('extract_from_unified_state_register', sa.String(), nullable=True),
    sa.Column('annual_report', sa.String(), nullable=True),
    sa.Column('privacy_policy', sa.String(), nullable=True),
    sa.Column('privacy_policy_en', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Feedback data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Foundation partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('description_en', sa.String(length=600), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Foundation team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('founder', sa.Boolean(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('description_en', sa.String(length=600), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Goals of the foundation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('description_en', sa.String(length=600), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Help in numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('photo_path_en', sa.String(), nullable=True),
    sa.Column('photo_path_adaptive', sa.String(), nullable=True),
    sa.Column('photo_path_adaptive_en', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('media_path', sa.String(), nullable=False),
    sa.Column('slogan', sa.String(length=100), nullable=False),
    sa.Column('slogan_en', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=False),
    sa.Column('call_to_action', sa.String(length=600), nullable=False),
    sa.Column('call_to_action_en', sa.String(length=600), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('History of the foundation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=False),
    sa.Column('media_path', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('header', sa.String(length=100), nullable=True),
    sa.Column('header_en', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=600), nullable=True),
    sa.Column('body_en', sa.String(length=600), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('title_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('description_en', sa.String(length=600), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Payment Details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('iban_code', sa.String(length=34), nullable=False),
    sa.Column('name_of_bank', sa.String(length=200), nullable=False),
    sa.Column('bank_address', sa.String(length=200), nullable=False),
    sa.Column('edrpou_code', sa.String(length=8), nullable=False),
    sa.Column('swift_code', sa.String(length=11), nullable=False),
    sa.Column('company_address', sa.String(length=200), nullable=False),
    sa.Column('correspondent_bank', sa.String(length=200), nullable=True),
    sa.Column('address_of_correspondent_bank', sa.String(length=200), nullable=True),
    sa.Column('account_of_the_correspondent_bank', sa.String(length=200), nullable=True),
    sa.Column('swift_code_of_the_correspondent_bank', sa.String(length=11), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Payment Details')
    op.drop_table('Payment')
    op.drop_table('History of the foundation')
    op.drop_table('Hero')
    op.drop_table('Help in numbers')
    op.drop_table('Goals of the foundation')
    op.drop_table('Foundation team')
    op.drop_table('Foundation partners')
    op.drop_table('Feedback data')
    op.drop_table('Docs and reports')
    op.drop_table('Current needs')
    op.drop_table('Counter')
    op.drop_table('Contacs')
    # ### end Alembic commands ###
