"""Default configuration

Use env var to override
"""
import os

ENV = os.getenv("FLASK_ENV")
DEBUG = ENV == "development"
SECRET_KEY = os.getenv("SECRET_KEY")

SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False

ADMIN_DEFAULT_LOGIN = os.getenv("ADMIN_DEFAULT_LOGIN")
ADMIN_DEFAULT_PASSWORD = os.getenv("ADMIN_DEFAULT_PASSWORD")
USER_DEFAULT_LOGIN = os.getenv("USER_DEFAULT_LOGIN")
USER_DEFAULT_PASSWORD = os.getenv("USER_PASSWORD")

BASE_URL = os.getenv("BASE_URL")
PAYPAL_CANCEL_URL = os.getenv("PAYPAL_CANCEL_URL")
MAIN_PAGE_URL = os.getenv("MAIN_PAGE_URL")

BABEL_DEFAULT_LOCALE = "uk_UA"

PAYPAL_MODE = os.getenv("PAYPAL_MODE") #sandbox or live
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")
FONDY_MERCHANT_ID = os.getenv("FONDY_MERCHANT_ID")
FONDY_SECRET_KEY = os.getenv("FONDY_SECRET_KEY")

MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_RECIPIENTS = os.getenv("MAIL_RECIPIENTS").split(" ")
